// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package payment

import (
	"github.com/google/wire"
	"github.com/tair/full-observability/internal/payment/domain"
	"github.com/tair/full-observability/internal/payment/handler"
	"github.com/tair/full-observability/internal/payment/repository"
	"github.com/tair/full-observability/internal/payment/usecase/command"
	"github.com/tair/full-observability/internal/payment/usecase/query"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHandler initializes payment handler with all dependencies
func InitializeHandler(db *gorm.DB) (*handler.PaymentHandler, error) {
	paymentRepository := ProvidePaymentRepository(db)
	createPaymentHandler := ProvideCreatePaymentHandler(paymentRepository)
	updateStatusHandler := ProvideUpdateStatusHandler(paymentRepository)
	getPaymentHandler := ProvideGetPaymentHandler(paymentRepository)
	listPaymentsHandler := ProvideListPaymentsHandler(paymentRepository)
	paymentHandler := handler.NewPaymentHandlerWithDI(createPaymentHandler, updateStatusHandler, getPaymentHandler, listPaymentsHandler, paymentRepository)
	return paymentHandler, nil
}

// wire.go:

// ProvidePaymentRepository provides the payment repository
func ProvidePaymentRepository(db *gorm.DB) domain.PaymentRepository {
	return repository.NewGormPaymentRepository(db)
}

// Command Handlers Providers
func ProvideCreatePaymentHandler(repo domain.PaymentRepository) *command.CreatePaymentHandler {
	return command.NewCreatePaymentHandler(repo)
}

func ProvideUpdateStatusHandler(repo domain.PaymentRepository) *command.UpdateStatusHandler {
	return command.NewUpdateStatusHandler(repo)
}

// Query Handlers Providers
func ProvideGetPaymentHandler(repo domain.PaymentRepository) *query.GetPaymentHandler {
	return query.NewGetPaymentHandler(repo)
}

func ProvideListPaymentsHandler(repo domain.PaymentRepository) *query.ListPaymentsHandler {
	return query.NewListPaymentsHandler(repo)
}

// Wire sets
var RepositorySet = wire.NewSet(
	ProvidePaymentRepository,
)

var CommandHandlerSet = wire.NewSet(
	ProvideCreatePaymentHandler,
	ProvideUpdateStatusHandler,
)

var QueryHandlerSet = wire.NewSet(
	ProvideGetPaymentHandler,
	ProvideListPaymentsHandler,
)

var AllHandlersSet = wire.NewSet(
	RepositorySet,
	CommandHandlerSet,
	QueryHandlerSet,
)
