// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inventory

import (
	"github.com/google/wire"
	"github.com/tair/full-observability/internal/inventory/delivery/http"
	"github.com/tair/full-observability/internal/inventory/domain"
	"github.com/tair/full-observability/internal/inventory/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHTTPHandler initializes HTTP handler with all dependencies
func InitializeHTTPHandler(db *gorm.DB) (*http.InventoryHandler, error) {
	inventoryRepository := ProvideInventoryRepository(db)
	inventoryHandler := http.NewInventoryHandler(inventoryRepository)
	return inventoryHandler, nil
}

// wire.go:

// ProvideInventoryRepository provides the inventory repository
func ProvideInventoryRepository(db *gorm.DB) domain.InventoryRepository {
	return repository.NewGormInventoryRepository(db)
}

// Wire sets
var RepositorySet = wire.NewSet(
	ProvideInventoryRepository,
)
